name: Pre Build

on:
  push:
    paths:
      - 'packages/**'
      - '!packages/**.md'
  pull_request:
    paths:
      - 'packages/**'
      - '!packages/**.md'

env:
  NODE_OPTIONS: --openssl-legacy-provider --no-experimental-strip-types

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'

    - name: Install dependencies and setup
      run: npm install && npm run setup

    - name: Build
      run: npm run build

    - name: Check build status
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded!"
        else
          echo "Build failed!"
          exit 1
        fi
